apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: policies-prj
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    # https://artifacthub.io/packages/helm/kyverno/kyverno
    targetRevision: 3.0.4 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
