apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring-prj
  sources:
  - repoURL: https://github.com/yreinhardt/argo-kyverno.git
    targetRevision: HEAD
    ref: valuesPath
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    targetRevision: 48.2.3 
    helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      # value file from external git repo (https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
      valueFiles:
      - $valuesPath/setup/values/values-prom.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
